module_name: Core Updater
compatible_versions: 1.0.5+
author: thirty bees
category: administration
tags:
  - update
  - upgrade
  - coreupdater
description_short: This module brings the tools for keeping your shop installation up to date.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: AFL 3.0
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
