module_name: Bees Blog Popular Posts
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - blog
  - blog module
  - bees blog
  - beesblog
  - beesblogpopularposts
  - widget
description_short: Popular posts widget for official thirty bees blog module
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
