module_name: Statistics Module
compatible_versions: 1.0.4+
author: thirty bees
category: statistics
tags:
  - stats
  - statistics
  - stats module
  - statsmodule
description_short: The Stats Module is the stats core for thirty bees statistic system.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
