module_name: Block Category Products
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - product page
  - crossselling
  - similar products
  - productscategory
description_short: Adds a block on the product page that displays products from the same category.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL 3.0
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
