module_name: Block Image Slider
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - home page
  - slider
  - image slider
  - homeslider
description_short: The home slider module adds a slider to you home page.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
