version: '3'

services:
  memcached:
    image: memcached:1.6.29
    restart: unless-stopped

  mysql:
    image: mariadb:11.4.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: thirtybees
      MYSQL_USER: thirtybees
      MYSQL_PASSWORD: thirtybees
      MYSQL_ROOT_PASSWORD: root

  thirtybees:
    image: "ghcr.io/wilsonify/thirtybees:1.0.0"
    ports:
      - "32080:80"  # Expose Nginx on host port 32080
    depends_on:
      - mysql
      - memcached
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
