version: '3'

services:
  memcached:
    image: memcached:1.6.29
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4.3
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: thirtybees
      MARIADB_USER: thirtybees
      MARIADB_PASSWORD: thirtybees
      MARIADB_ROOT_PASSWORD: root

  dbgate:
    image: dbgate/dbgate:alpine
    restart: unless-stopped
    ports:
      - "31000:3000"

  thirtybees:
    image: "ghcr.io/wilsonify/thirtybees:1.0.0"
    ports:
      - "32080:80"
    depends_on:
      - mariadb
      - memcached
    restart: unless-stopped
    environment:
      MARIADB_USER: thirtybees
      MARIADB_PASSWORD: thirtybees
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
