version: '3'

services:
  memcached:
    image: memcached:1.6.29
    restart: unless-stopped
  mysql:
    image: mariadb:11.4.3
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=thirtybees
      - MYSQL_USER=thirtybees
      - MYSQL_PASSWORD=thirtybees
      - MYSQL_ROOT_PASSWORD=root
  php:
    depends_on: [ mysql,memcached ]
    restart: unless-stopped
    image: "ghcr.io/wilsonify/thirtybees:1.0.0"
    volumes:
      - ./www:/var/www/default
  web:
    depends_on: [ php ]
    restart: unless-stopped
    image: nginx:1.27.1
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/default
      - ./default.conf:/etc/nginx/conf.d/default.conf
