module_name: Block Social Sharing
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - social sharing
  - facebook share
  - twitter share
  - socialsharing
description_short: The Social Sharing module allows you to place a block on the product pages letting customers share your products.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
