module_name: Bankwire Module
compatible_versions: 1.0.0+
author: thirty bees
category: payment
tags:
  - bankwire
  - bank payment
  - payment module
description_short: Accept bank wires easily with your thirty bees shop using our bank wire module.
description: description.md
images:
  - image-1.png
  - image-2.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
