# Cloudflare Tunnel Configuration
tunnel: 13395bf3-fd34-4abe-bc78-ebe1e26aa55f
ingress:
  # Dev environment (Docker Compose)
  - hostname: thirtybees-dev.renewed-renaissance.com
    service: http://localhost:40080

  # Prod environment
  - hostname: thirtybees.renewed-renaissance.com
    path: prod
    service: http://192.168.1.128:40082

  # Catch-all rule (required)
  - service: http_status:404
