services:

  cloudflared:
    build:
      context: ../../src/cloudflared
    restart: unless-stopped
    env_file: .env
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yaml run --token $CLOUD_FLARE_TOKEN
    volumes:
      - ./config.yaml:/etc/cloudflared/config.yaml:ro
    depends_on:
      - thirtybees
    network_mode: host

  memcached:
    build:
      context: ../../src/memcached
    restart: unless-stopped
    networks:
      - thirtybees-network

  mariadb:
    build:
      context: ../../src/db
    restart: unless-stopped
    env_file: .env
    networks:
      - thirtybees-network
    volumes:
      - mariadb-data:/var/lib/mysql

  thirtybees:
    build:
      context: ../../src/thirtybees
    ports:
      - "40080:80"
    depends_on:
      - mariadb
      - memcached
    restart: unless-stopped
    env_file: .env
    environment:
      - SHOP_DOMAIN=${SHOP_DOMAIN}
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - thirtybees-network
    volumes:
      - thirtybees-config:/var/www/default/config
      - thirtybees-img:/var/www/default/img
      - thirtybees-modules:/var/www/default/modules
      - thirtybees-themes:/var/www/default/themes
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  thirtybees-network:
    driver: bridge

volumes:
  mariadb-data:
  thirtybees-config:
  thirtybees-img:
  thirtybees-modules:
  thirtybees-themes:
