module_name: Block Currencies
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - currencies
  - currency
  - exchange
  - localization
  - blockcurrencies
description_short: The block currencies allows your customers to change between supported currencies on the front of your shop.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
