module_name: Block Product Payment Logos
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - payment
  - logo
  - productpaymentlogos
description_short: The Product Payment Logo module will allow you to display payment logos on your product page.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
