module_name: Block Tags
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - tags
  - seo
  - tag
  - blocktags
description_short: The block tags adds a tag cloud to your site.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
