apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thirtybees-prod

resources:
  - namespace.yaml
  - thirtybees-configmap.yaml
  - thirtybees-secrets.enc.yaml
  - php-deployment.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - cloudflared-secret.yaml
  - cloudflared-deployment.yaml

commonLabels:
  app.kubernetes.io/name: thirtybees
  app.kubernetes.io/instance: prod
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/wilsonify/thirtybees
    newTag: latest
  - name: nginx
    newName: nginx
    newTag: alpine
  - name: cloudflare/cloudflared
    newTag: latest
