module_name: Block Manufacturers
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - manufacturer
  - brand
  - manufacturers
  - blockmanufacturer
description_short: The block manufacturer allows you to dislay a block link manufacturers
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
