module_name: Send to a Friend Module
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - refferal
  - send to a friend
  - advertising
  - sendtoafriend
description_short: Send to a Friend module allows you put put a link to send products to customers friends.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
