module_name: Template Manager
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - theme
  - template manager
  - thememanager
description_short: The template manager module allows you to switch between templates for product, cms, and category pages.
description: description.md
images:
  - image-1.png
  - image-2.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
