module_name: Block CMS Info
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - cms pages
  - cms
  - cms links
  - blockcmsinfo
description_short: The block CMS Info module allows you to add custom text to areas of your site
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
