module_name: Block Facebook Share
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - facebook
  - social media
  - social sharing
  - blocksharefb
description_short: The block Facebook share module allows you to add a facebook share button to your product pages.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
