apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dbgate
  name: dbgate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbgate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --chart
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: dbgate
    spec:
      containers:
        - image: dbgate/dbgate:alpine
          name: dbgate
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
