apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dbgate
  name: dbgate
spec:
  ports:
    - name: "31000"
      port: 31000
      targetPort: 3000
  selector:
    io.kompose.service: dbgate
