apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image }}"
          env:
            - name: MYSQL_DATABASE
              value: "{{ .Values.mariadb.mariadbDatabase }}"
            - name: MYSQL_USER
              value: "{{ .Values.mariadb.mariadbUser }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mariadb.mariadbPassword }}"
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mariadb.mariadbRootPassword }}"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mariadb
