apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --chart
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: thirtybees
            - name: MARIADB_PASSWORD
              value: thirtybees
            - name: MARIADB_ROOT_PASSWORD
              value: root
            - name: MARIADB_USER
              value: thirtybees
          image: mariadb:11.4.3
          name: mariadb
      restartPolicy: Always
