apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: thirtybees
  name: thirtybees
spec:
  ports:
    - name: "32080"
      port: 32080
      targetPort: 80
  selector:
    io.kompose.service: thirtybees
