module_name: ECB Exchange Rate Services
compatible_versions: 1.0.0+
author: thirty bees
category: administration
tags:
  - payment
  - currency
  - exchange rates
  - ecbexchange
description_short: Fetches currency exchange rates from the European Central Bank.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: AFL 3.0
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
