module_name: Dashboard Activity
compatible_versions: 1.0.0+
author: thirty bees
category: statistics
tags:
  - dashboard
  - shop activity
  - stats
  - statistics
  - dashactivity
description_short: Show recent users and other statistics.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
