module_name: Block User Info
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - login
  - user information
  - customer login
  - blockuserinfo
description_short: The block user info block adds a login link to the top of your site
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
